FROM ubuntu:latest
LABEL AUTHOR="Martins"

ARG APIMATION_VERSION=0.55.0
ENV VERSION=${APIMATION_VERSION}

RUN apt update && apt upgrade
RUN apt install unzip -y

WORKDIR /usr/src/apimation
ADD https://github.com/apimation/cli-client/releases/download/v${APIMATION_VERSION}/apimation_${APIMATION_VERSION}_linux_amd64.zip .
RUN unzip apimation_${APIMATION_VERSION}_linux_amd64.zip
RUN rm apimation_${APIMATION_VERSION}_linux_amd64.zip

ENTRYPOINT [ "./apimation" ]
