CREATE DATABASE test_users;
USE test_users;
CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT, alias VARCHAR(255) NOT NULL, creation_date DATETIME DEFAULT CURRENT_TIMESTAMP, active BOOLEAN DEFAULT 1);

INSERT INTO users(alias) VALUES('admin');
